module.exports = (client, Embed) => {
    const küfür = [
        "mq",
        "aq",
        "mına koyim",
        "ına koyim",
        "ına koyayım",
        "ina koyayım",
        "ına koyayim",
        "ina koyayim",
        "mina koyim",
        "amine",
        "döl",
        "sg",
        "oç",
        "oçe",
        "ananı sikim",
        "anneni sikim",
        "anneni sikeyim",
        "ananı sikeyim",
        "ağzına",
        "ağzına sıçim",
        "ağzına sıçayım",
        "ağzına s",
        "siktir",
        "fuck",
        "puşt",
        "pust",
        "piç",
        "sikerim",
        "sik",
        "yara",
        "yarra",
        "yarrak",
        "yarak",
        "amcık",
        "orospu",
        "orosbu",
        "oç",
        ".oc",
        "ibne",
        "yavşak",
        "bitch",
        "dalyarak",
        "amk",
        "awk",
        "taşak",
        "taşşak",
        "daşak",
        "daşşak",
        "sikm",
        "sikim",
        "sikmm",
        "skim",
        "skm",
        "sg",
        "öç",
        "AQ",
        "AQI",
        "AQİ",
        "shit"
      ];
      if(küfür.some(siu => message.content.includes(siu))) 
}